development:
  adapter: postgresql
  encoding: unicode
  database: raffle_dev
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: raffle_production
  pool: 5
  username: postgres
  password: postgres